CREATE TABLE IF NOT EXISTS schema_migrations (
    version VARCHAR(255) PRIMARY KEY,
    checksum CHAR(64) NOT NULL,
    applied_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE OR REPLACE FUNCTION shuttleai_set_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$;

CREATE TABLE IF NOT EXISTS regions (
    id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(32) NOT NULL UNIQUE,
    name TEXT NOT NULL,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS routes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    region_id SMALLINT NOT NULL REFERENCES regions(id) ON DELETE RESTRICT,
    name TEXT NOT NULL,
    trip_type TEXT NOT NULL CHECK (trip_type IN ('morning', 'evening')),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_routes_region_name UNIQUE (region_id, name)
);

CREATE TABLE IF NOT EXISTS stops (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    region_id SMALLINT NOT NULL REFERENCES regions(id) ON DELETE RESTRICT,
    name TEXT NOT NULL,
    latitude NUMERIC(9,6) NOT NULL CHECK (latitude BETWEEN -90 AND 90),
    longitude NUMERIC(10,6) NOT NULL CHECK (longitude BETWEEN -180 AND 180),
    grid_x SMALLINT NOT NULL,
    grid_y SMALLINT NOT NULL,
    geocode_status TEXT,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS route_stops (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    route_id BIGINT NOT NULL REFERENCES routes(id) ON DELETE CASCADE,
    stop_id BIGINT NOT NULL REFERENCES stops(id) ON DELETE RESTRICT,
    stop_order SMALLINT NOT NULL CHECK (stop_order >= 1),
    scheduled_time TIME,
    boarding_allowed BOOLEAN NOT NULL,
    alighting_allowed BOOLEAN NOT NULL,
    is_default_dropoff BOOLEAN NOT NULL DEFAULT FALSE,
    source_kind TEXT NOT NULL CHECK (source_kind IN ('document', 'system_default', 'manual')),
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_route_stops_route_order UNIQUE (route_id, stop_order),
    CONSTRAINT uq_route_stops_id_route UNIQUE (id, route_id)
);

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kakao_user_id BIGINT NOT NULL UNIQUE,
    nickname TEXT,
    role TEXT NOT NULL DEFAULT 'user' CHECK (role IN ('user', 'admin')),
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    last_login_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS kakao_credentials (
    user_id BIGINT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    access_token_ciphertext BYTEA,
    refresh_token_ciphertext BYTEA,
    access_token_expires_at TIMESTAMPTZ,
    refresh_token_expires_at TIMESTAMPTZ,
    token_updated_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS notification_settings (
    user_id BIGINT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    exclude_holidays BOOLEAN NOT NULL DEFAULT TRUE,
    timezone TEXT NOT NULL DEFAULT 'Asia/Seoul',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS notification_active_days (
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    weekday SMALLINT NOT NULL CHECK (weekday BETWEEN 0 AND 6),
    PRIMARY KEY (user_id, weekday)
);

CREATE TABLE IF NOT EXISTS favorites (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    route_id BIGINT NOT NULL REFERENCES routes(id) ON DELETE RESTRICT,
    boarding_route_stop_id BIGINT NOT NULL,
    alighting_route_stop_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_favorites_boarding_route_stop
        FOREIGN KEY (boarding_route_stop_id, route_id)
        REFERENCES route_stops(id, route_id) ON DELETE RESTRICT,
    CONSTRAINT fk_favorites_alighting_route_stop
        FOREIGN KEY (alighting_route_stop_id, route_id)
        REFERENCES route_stops(id, route_id) ON DELETE RESTRICT,
    CONSTRAINT uq_favorites_selection
        UNIQUE (user_id, route_id, boarding_route_stop_id, alighting_route_stop_id)
);

CREATE TABLE IF NOT EXISTS favorite_notifications (
    favorite_id BIGINT PRIMARY KEY REFERENCES favorites(id) ON DELETE CASCADE,
    enabled BOOLEAN NOT NULL DEFAULT FALSE,
    lead_minutes SMALLINT NOT NULL DEFAULT 10 CHECK (lead_minutes BETWEEN 1 AND 180),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS push_subscriptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    endpoint TEXT NOT NULL,
    endpoint_hash CHAR(64) NOT NULL UNIQUE CHECK (endpoint_hash ~ '^[0-9a-fA-F]{64}$'),
    p256dh TEXT NOT NULL,
    auth TEXT NOT NULL,
    expiration_time TIMESTAMPTZ,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    platform TEXT,
    user_agent TEXT,
    device_label TEXT,
    last_seen_at TIMESTAMPTZ,
    owner_changed_at TIMESTAMPTZ,
    revoked_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_routes_region_active_name
    ON routes (region_id, active, name);
CREATE INDEX IF NOT EXISTS idx_stops_region_name
    ON stops (region_id, name);
CREATE INDEX IF NOT EXISTS idx_route_stops_scheduled_time
    ON route_stops (route_id, scheduled_time)
    WHERE scheduled_time IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS uq_route_stops_default_dropoff
    ON route_stops (route_id)
    WHERE is_default_dropoff;
CREATE INDEX IF NOT EXISTS idx_notification_days_weekday_user
    ON notification_active_days (weekday, user_id);
CREATE INDEX IF NOT EXISTS idx_favorite_notifications_enabled
    ON favorite_notifications (favorite_id)
    WHERE enabled;
CREATE INDEX IF NOT EXISTS idx_push_subscriptions_enabled_user
    ON push_subscriptions (user_id)
    WHERE enabled;
CREATE INDEX IF NOT EXISTS idx_push_subscriptions_enabled_expiration
    ON push_subscriptions (expiration_time)
    WHERE enabled AND expiration_time IS NOT NULL;

DROP TRIGGER IF EXISTS trg_regions_updated_at ON regions;
CREATE TRIGGER trg_regions_updated_at BEFORE UPDATE ON regions
FOR EACH ROW EXECUTE FUNCTION shuttleai_set_updated_at();
DROP TRIGGER IF EXISTS trg_routes_updated_at ON routes;
CREATE TRIGGER trg_routes_updated_at BEFORE UPDATE ON routes
FOR EACH ROW EXECUTE FUNCTION shuttleai_set_updated_at();
DROP TRIGGER IF EXISTS trg_stops_updated_at ON stops;
CREATE TRIGGER trg_stops_updated_at BEFORE UPDATE ON stops
FOR EACH ROW EXECUTE FUNCTION shuttleai_set_updated_at();
DROP TRIGGER IF EXISTS trg_route_stops_updated_at ON route_stops;
CREATE TRIGGER trg_route_stops_updated_at BEFORE UPDATE ON route_stops
FOR EACH ROW EXECUTE FUNCTION shuttleai_set_updated_at();
DROP TRIGGER IF EXISTS trg_users_updated_at ON users;
CREATE TRIGGER trg_users_updated_at BEFORE UPDATE ON users
FOR EACH ROW EXECUTE FUNCTION shuttleai_set_updated_at();
DROP TRIGGER IF EXISTS trg_kakao_credentials_updated_at ON kakao_credentials;
CREATE TRIGGER trg_kakao_credentials_updated_at BEFORE UPDATE ON kakao_credentials
FOR EACH ROW EXECUTE FUNCTION shuttleai_set_updated_at();
DROP TRIGGER IF EXISTS trg_notification_settings_updated_at ON notification_settings;
CREATE TRIGGER trg_notification_settings_updated_at BEFORE UPDATE ON notification_settings
FOR EACH ROW EXECUTE FUNCTION shuttleai_set_updated_at();
DROP TRIGGER IF EXISTS trg_favorites_updated_at ON favorites;
CREATE TRIGGER trg_favorites_updated_at BEFORE UPDATE ON favorites
FOR EACH ROW EXECUTE FUNCTION shuttleai_set_updated_at();
DROP TRIGGER IF EXISTS trg_favorite_notifications_updated_at ON favorite_notifications;
CREATE TRIGGER trg_favorite_notifications_updated_at BEFORE UPDATE ON favorite_notifications
FOR EACH ROW EXECUTE FUNCTION shuttleai_set_updated_at();
DROP TRIGGER IF EXISTS trg_push_subscriptions_updated_at ON push_subscriptions;
CREATE TRIGGER trg_push_subscriptions_updated_at BEFORE UPDATE ON push_subscriptions
FOR EACH ROW EXECUTE FUNCTION shuttleai_set_updated_at();

INSERT INTO regions (code, name)
VALUES ('gyeonggi', '경기'), ('seoul', '서울')
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name;
