CREATE TABLE IF NOT EXISTS notification_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    favorite_id BIGINT REFERENCES favorites(id) ON DELETE SET NULL,
    service_date DATE NOT NULL,
    scheduled_time TIME NOT NULL,
    effective_channel TEXT NOT NULL CHECK (effective_channel IN ('PUSH', 'KAKAO')),
    status TEXT NOT NULL DEFAULT 'PROCESSING'
        CHECK (status IN ('PROCESSING', 'SUCCESS', 'PARTIAL', 'FAILED', 'SKIPPED')),
    error_code TEXT CHECK (error_code IN (
        'NO_PUSH_SUBSCRIPTION', 'PUSH_EXPIRED', 'PUSH_SEND_FAILED',
        'KAKAO_SEND_FAILED', 'WEATHER_UNAVAILABLE'
    )),
    started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    completed_at TIMESTAMPTZ,
    CONSTRAINT uq_notification_runs_logical
        UNIQUE (user_id, favorite_id, service_date, scheduled_time)
);

CREATE TABLE IF NOT EXISTS notification_deliveries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    notification_run_id BIGINT NOT NULL
        REFERENCES notification_runs(id) ON DELETE CASCADE,
    channel TEXT NOT NULL CHECK (channel IN ('PUSH', 'KAKAO')),
    push_subscription_id BIGINT
        REFERENCES push_subscriptions(id) ON DELETE SET NULL,
    status TEXT NOT NULL DEFAULT 'PROCESSING'
        CHECK (status IN ('PROCESSING', 'SUCCESS', 'FAILED', 'EXPIRED')),
    error_code TEXT CHECK (error_code IN (
        'PUSH_EXPIRED', 'PUSH_SEND_FAILED', 'KAKAO_SEND_FAILED'
    )),
    attempted_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    completed_at TIMESTAMPTZ,
    CONSTRAINT ck_notification_delivery_subscription CHECK (
        (channel = 'PUSH' AND push_subscription_id IS NOT NULL)
        OR (channel = 'KAKAO' AND push_subscription_id IS NULL)
    )
);

CREATE INDEX IF NOT EXISTS idx_notification_runs_service_status
    ON notification_runs (service_date, status);
CREATE INDEX IF NOT EXISTS idx_notification_runs_user_started
    ON notification_runs (user_id, started_at DESC);
CREATE INDEX IF NOT EXISTS idx_notification_deliveries_run
    ON notification_deliveries (notification_run_id, id);
CREATE INDEX IF NOT EXISTS idx_notification_deliveries_subscription
    ON notification_deliveries (push_subscription_id)
    WHERE push_subscription_id IS NOT NULL;
