CREATE TABLE IF NOT EXISTS scheduled_push_tests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    scheduled_at TIMESTAMPTZ NOT NULL,
    message TEXT NOT NULL CHECK (char_length(message) BETWEEN 1 AND 500),
    urgency TEXT NOT NULL DEFAULT 'normal'
        CHECK (urgency IN ('normal', 'high')),
    ttl_seconds INTEGER NOT NULL DEFAULT 60 CHECK (ttl_seconds = 60),
    target_subscription_ids BIGINT[],
    status TEXT NOT NULL DEFAULT 'SCHEDULED'
        CHECK (status IN ('SCHEDULED', 'PROCESSING', 'SUCCESS', 'PARTIAL', 'FAILED')),
    error_code TEXT CHECK (error_code IN (
        'NO_PUSH_SUBSCRIPTION', 'PUSH_EXPIRED', 'PUSH_SEND_FAILED'
    )),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    worker_started_at TIMESTAMPTZ,
    send_completed_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS scheduled_push_test_deliveries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scheduled_push_test_id BIGINT NOT NULL
        REFERENCES scheduled_push_tests(id) ON DELETE CASCADE,
    push_subscription_id BIGINT
        REFERENCES push_subscriptions(id) ON DELETE SET NULL,
    status TEXT NOT NULL DEFAULT 'PROCESSING'
        CHECK (status IN ('PROCESSING', 'SUCCESS', 'FAILED', 'EXPIRED')),
    error_code TEXT CHECK (error_code IN ('PUSH_EXPIRED', 'PUSH_SEND_FAILED')),
    attempted_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    send_completed_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_scheduled_push_tests_due
    ON scheduled_push_tests (scheduled_at, id)
    WHERE status='SCHEDULED';
CREATE INDEX IF NOT EXISTS idx_scheduled_push_tests_user_created
    ON scheduled_push_tests (user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_scheduled_push_test_deliveries_test
    ON scheduled_push_test_deliveries (scheduled_push_test_id, id);
